spring.application.name=sistema_chamado

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/chamadas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=#Familias1122
spring.jpa.hibernate.ddl-auto=update
